#!/bin/bash

source $XDG_CONFIG_HOME/dwmbar/config.sh

declare -A signals

OLDIFS=$IFS
IFS=$'\n'
for line in $(cat $SETUP) ; do
    IFS=' ' read -r key sig <<<$(echo $line | tr -s ' ' | cut -d' ' -f1,3)
    signals[$key]="$sig"
done
IFS=$OLDIFS

sendSignal() {
    pkill -RTMIN+${signals["$1"]} dwmbar
}

listenACPI() {
    acpi_listen | while read -r line ; do
        case "$line" in
            button/mute*)           sendSignal "volume" ;;
            button/volumeup*)       sendSignal "volume" ;;
            button/volumedown*)     sendSignal "volume" ;;
            video/brightnessup*)    sendSignal "bright" ;;
            video/brightnessdown*)  sendSignal "bright" ;;
            ac_adapter*)            sendSignal "battery" ;;
            battery*)               sendSignal "battery" ;;
        esac
    done
}

listenPlayer() {
    while :; do
        mpc idle >/dev/null && sendSignal "player" || sleep 1
    done
}

listenXKB() {
    while :; do
        xkb-switch -w && sendSignal "layout"
    done
}

listenXKB &
listenPlayer &
listenACPI &

sleep infinity
