#!/bin/bash

source $XDG_CONFIG_HOME/dwmbar/config.sh

declare -A signals

OLDIFS=$IFS
IFS=$'\n'
for line in $(cat $SETUP) ; do
    IFS=' ' read -r key sig <<<$(echo $line | tr -s ' ' | cut -d' ' -f1,3)
    signals[$key]="$sig"
done
IFS=$OLDIFS

sendSignal() {
    pkill -RTMIN+${signals["$1"]} dwmbar
}

listenACPI() {
    acpi_listen | while read -r line ; do
        case "$line" in
            button/mute*)           sendSignal "volume" ;;
            button/volumeup*)       sendSignal "volume" ;;
            button/volumedown*)     sendSignal "volume" ;;
            video/brightnessup*)    sendSignal "bright" ;;
            video/brightnessdown*)  sendSignal "bright" ;;
            ac_adapter*)            sendSignal "battery" ;;
            battery*)               sendSignal "battery" ;;
        esac
    done
}

listenPlayer() {
    while :; do
        mpc idle >/dev/null && sendSignal "player"
    done
}

listenXKB() {
    while :; do
        xkb-switch -w && sendSignal "keyboard"
    done
}

kill_descendant_processes() {
    local pid="$1"
    local and_self="${2:-false}"
    if children="$(pgrep -P "$pid")"; then
        for child in $children; do
            kill_descendant_processes "$child" true
        done
    fi
    if [[ "$and_self" == true ]]; then
        kill "$pid"
    fi
}

listenXKB &
listenPlayer &
listenACPI &

trap "kill_descendant_processes $$" INT

exec sleep infinity
