#!/usr/bin/env bash

# Show 📡 and percent strength if connected to wifi
# Show 📶 if connected to ethernet
# Show ❎ if none.

case $BLOCK_BUTTON in
    3) setsid "$TERMINAL" -e nmtui & ;;
    1) notify-send "🌐 Internet module" "\- Click to connect
📡: wifi connection with quality
📶: ethernet connection
❎: no ethernet/wifi connection
❓: unknown ethernet status
" ;;
esac

if grep -q "down" /sys/class/net/w*/operstate ; then
    sed "s/down/❎/;s/up/📶/;s/unknown/❓/" /sys/class/net/e*/operstate
else
    grep "^\s*w" /proc/net/wireless | awk '{ print "📡", int($3 * 100 / 70) }'
fi
