#!/usr/bin/env bash

format="🎹 <song> <stat>"
name_length=60

case $BLOCK_BUTTON in
    1) playerctl play-pause >/dev/null 2>&1 ;;
    3) setsid "$TERMINAL" -e ncmpcpp >/dev/null 2>&1 & ;;
    4) playerctl previos >/dev/null 2>&1 ;;
    5) playerctl next >/dev/null 2>&1 ;;
esac

status=$(playerctl status 2>&1 | tr '[:upper:]' '[:lower:]')
case "$status" in
    stopped)    echo "$format" | sed -n "s/<song>/Player stopped/g ; s/<stat>/⏹/gp" && exit ;;
    no*)        echo "$format" | sed -n "s/<song>/No players found/g ; s/<stat>/⏹/gp" && exit ;;
    playing)    stat='⏸' ;;
    paused)     stat='▶' ;;
    *)          stat='❓' ;;
esac

song=$(playerctl metadata --format "{{ artist }} - {{ title }}")

[[ "$song" == " - "* ]] && song="${song:3}"

[ "${#song}" -gt $name_length ] && song="${song:0:$((name_length - 3))}..."

song="$(echo "$song" | sed 's/&/\\\\&/g ; s/"/\\"/g')"
echo "$format" | awk "{ gsub(\"<song>\",\"${song}\",\$0); gsub(\"<stat>\",\"${stat}\",\$0); printf \$0 }"
