#!/bin/bash

case $BLOCK_BUTTON in
	1) pulsemixer --toggle-mute ;;
	3) setsid $TERMINAL -e pulsemixer & ;;
	4) pulsemixer --change-volume -3 ;;
	5) pulsemixer --change-volume +3 ;;
esac

level=$(pulsemixer --get-volume | cut -d' ' -f1)
status=$(pulsemixer --get-mute)

[[ $status -eq 0 ]] && echo "🔊 $level%" && exit
echo "🔇 $level%" && exit

# case $BLOCK_BUTTON in
# 	1) amixer set Master toggle >/dev/null ;;
# 	3) $TERMINAL -e alsamixer & disown ;;
# 	4) amixer set Master 5- >/dev/null ;;
# 	5) amixer set Master 5+ >/dev/null ;;
# esac

# read level stat < <(amixer get Master | \
#     tail -n1 | \
#     tr -d "[]%" | \
#     sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | \
#     # cut -d ' ' -f4,6)
#     cut -d ' ' -f5,6) # when pulse

# [[ $stat = "on" ]] && echo "🔊 $level%" && exit
# echo "🔇 $level%" && exit
