#!/bin/bash

case $BLOCK_BUTTON in
	1) amixer set Master toggle >/dev/null ;;
	3) $TERMINAL -e alsamixer & disown ;;
	4) amixer set Master 5- >/dev/null ;;
	5) amixer set Master 5+ >/dev/null ;;
esac

read level stat < <(amixer get Master | tail -n1 | tr -d "[]%" | cut -d ' ' -f6,8)

[[ $stat = "on" ]] && echo "🔊 $level%" && exit
echo "🔇 $level%" && exit
