name: C

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get -y install libx11-dev
    - name: make
      run: make
